version: "2.4" # optional since v1.27.0
services:
  middleware-1:
    restart: always
    image: oop2_studentrunner
    environment:      
      JMAP_MIDDLEWARE_PORT: "${MW_PORT:-8010}"
      JMAP_BACKEND_TARGET: "${BACKEND_TARGET:-backend-1:8020}"
    command: mvn -pl middleware exec:java
    cpus: 1
    mem_limit: 1G
    networks:
      - oop2_jmap
    ports:
      - 8010:8010
  backend-1:
    restart: always
    image: oop2_studentrunner
    environment:
      JMAP_BACKEND_PORT: "${BE_PORT:-8020}"
      JMAP_BACKEND_OSMFILE: "${OSM_FILE:-/jmap/data/styria_reduced.osm}"
    command: mvn -pl backend exec:java
    cpus: 4.0
    mem_limit: 4G
    volumes:
      - ./data:/jmap/data
    networks:
      - oop2_jmap
    # remove later
#    ports:
#      - 8020:8020
  frontend-1:
    restart: always
    image: nginx
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - oop2_jmap
    ports:
      - 8042:80
networks:
  oop2_jmap:
    external: false
    name: oop2_jmap
